datasets:
  recipe1M_inst: # name of the dataset builder
    # dataset_card: dataset_card/avsd_dialogue.md # path to the dataset card
    data_type: images # [images|videos|features] we use features in this case for extracted video features

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /nfs_share2/code/donghee/inversecooking/data/recipe1m_train.pkl
          storage: /nfs_share2/code/donghee/inversecooking/data/recipe1m_train.pkl
        val:
          url: /nfs_share2/code/donghee/inversecooking/data/recipe1m_val.pkl
          storage: /nfs_share2/code/donghee/inversecooking/data/recipe1m_val.pkl
        test:
          url: /nfs_share2/code/donghee/inversecooking/data/recipe1m_test.pkl
          storage: /nfs_share2/code/donghee/inversecooking/data/recipe1m_test.pkl
      images:
        storage: /home/donghee/im2recipe-Pytorch/1M